In [1]:
import torch

# 使用不包含可训练权重的自注意力机制来计算关于输入向量的上下文向量
计算步骤：
1. 构造一个输入矩阵Inputs
2. 计算注意力分数，即：attention_scores = Inputs @ Inputs.T
3. 将注意力分数归一化，即：attention_weights = softmax(attention_scores, dim=1)
4. 将注意力分数与输入矩阵相乘，得到上下文向量，即：contexts = softmax(attention_scores) @ Inputs

In [2]:
# 1. 构造一个输入矩阵inputs
# 以“Your journey starts with one step”为例，并将其转换为嵌入向量：
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)
print(f"inputs' shape is: {inputs.shape}")

inputs' shape is: torch.Size([6, 3])


In [3]:
# 2. 计算注意力分数，即：attention_scores = Inputs @ Inputs.T
attention_scores = inputs @ inputs.T
print(f"attention_scores' shape is: {attention_scores.shape}")
print(f"attention_scores is:\n{attention_scores}")

attention_scores' shape is: torch.Size([6, 6])
attention_scores is:
tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [5]:
# 3. 将注意力分数归一化，即：softmax(attention_scores)
attention_weights = torch.softmax(attention_scores, dim=1)
print(f"attention_weights' shape is: {attention_weights.shape}")
print(f"attention_weights is:\n{attention_weights}")
# 验证attention_weights的每一行的综合为1：
# print(f"attention_weights.sum(dim=1) is:\n{attention_weights.sum(dim=1)}")
print("attention_weights的每一行总和为：")
attention_weights_sum_per_row = attention_weights.sum(dim=1)
print(attention_weights_sum_per_row)

attention_weights' shape is: torch.Size([6, 6])
attention_weights is:
tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])
attention_weights的每一行总和为：
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [16]:
# 4. 将注意力分数与输入矩阵相乘，得到上下文向量
contexts = attention_weights @ inputs
print(f"contexts' shape is: {contexts.shape}, and it's dtype is: {contexts.dtype}")
print(f"contexts are: \n{contexts}")
# 验证上下文向量是否符合预期：
expected = torch.tensor(
    [[0.4421, 0.5931, 0.5790],
     [0.4419, 0.6515, 0.5683],
     [0.4431, 0.6496, 0.5671],
     [0.4304, 0.6298, 0.5510],
     [0.4671, 0.5910, 0.5266],
     [0.4177, 0.6503, 0.5645]],
     dtype=torch.float32
)
# assert torch.equal(contexts, expected)
# print(expected)
# 对于浮点数类型的两个张量的比较，需要允许误差的存在，例如这里可以设定误差为：1e-4
assert torch.allclose(contexts, expected, atol=1e-4)


contexts' shape is: torch.Size([6, 3]), and it's dtype is: torch.float32
contexts are: 
tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])
